import logging

from app.agents.base.agent import BaseAgent
from app.schemas.agent import AgentInput, AgentOutput, AgentStatus
from app.services.llm import BaseLLMProvider, LLMMessage
from app.state.task_state import TaskState

logger = logging.getLogger(__name__)

_CHAT_SYSTEM = """\
You are a helpful research assistant. Engage in friendly, informative conversation.
Help the user clarify their research goals, explain concepts, and provide context.
When your answer includes mathematical formulas: inline formulas use $...$, block formulas use $$...$$. \
Never output bare LaTeX without delimiters and never put formulas in code blocks.\
If the user message contains image_context generated by analyze_image_tool, use that context first. \
For paper screenshots, figures, formulas, tables, or charts, answer in a research-reading style. \
For error screenshots, identify likely causes and practical debugging steps. \
Do not claim visual details that are not present in the provided image_context.\
"""


class ChatAgent(BaseAgent):
    name = "chat_agent"
    description = "Handles general conversation, clarification, and user interaction."

    def __init__(self, llm: BaseLLMProvider) -> None:
        self.llm = llm

    async def run(self, agent_input: AgentInput, state: TaskState) -> AgentOutput:
        user_message: str = agent_input.input_data.get("user_message", agent_input.user_goal)
        history: list[dict] = agent_input.input_data.get("conversation_history", [])

        state.update_stage("general_chat", self.name)

        messages = [LLMMessage(role=m["role"], content=m["content"]) for m in history]
        messages.append(LLMMessage(role="user", content=user_message))

        try:
            llm_resp = await self.llm.complete(
                messages=messages,
                system=_CHAT_SYSTEM,
            )
            reply = llm_resp.content
        except Exception as exc:
            logger.warning("ChatAgent LLM call failed: %s", exc)
            reply = "I'm here to help with your research. Could you tell me more about what you're looking for?"

        return AgentOutput(
            task_id=agent_input.task_id,
            session_id=agent_input.session_id,
            agent_name=self.name,
            status=AgentStatus.SUCCESS,
            result={"reply": reply},
            next_suggestion="continue_chat_or_dispatch",
        )
